### ISSUE TITLE
 ‘replace’ was not declared in this scope

### ISSUE THREAD

**Issue by jpjarnoux** [michauorin/kofamparse#1]
Hi,
I'm trying to use your parse but I got this error : 
```
error: ‘replace’ was not declared in this scope
```
I never code in C++ so I don't understand.
Thanks

**Comment by michauorin** [comment]
Hello, thank You very much for bringing this issue to my attention!

I will fix it right away when i get back home, as it turns out my compiler probably has a non standard c++ STD library,
for GCC / G++ to compile it correctly an additional #include\<algorithm> is necessary.
I thought the function std::replace is a part of the \<string> library, but apparently it's in \<algorithm> now.

You can just add the missing line in the .cpp file (right below #include\<string>), or do a git pull when i commit the fix, but this will probably be in the evening CEST.

**Comment by jpjarnoux** [comment]
Thanks,
I could to test and it's working. Thanks for your help.
